### ISSUE TITLE
Eclipse Neon 2.0 Uploader not found EV3duder.exe in C:\ev3\uploader

### ISSUE THREAD

**Issue by Paul330** [c4ev3/EV3-Eclipse-Plugin#2]
Hello I am pretty new to this topic and Eclipse and I hope you can help or know someone who can support me. I installed Eclipse Neon 2.0 cpp and wanted to test the EV3 "Hello World". But when I try to upload and run the programm I always get a message Uploader not found "Ev3duder couldn't be found in !
When I press OK, I get the message The project's uploader path <> is invalid. Try correcting it. But how?

When I start a new project I define the path with C:\ev3\uploader as it is installed automatically. But when I open project\properties\C/C++ Build\Setting\Toolchains --> The line EV3 Uploader (ev3duder) is empty. I tried to use the browse button and copied the path from the explorer but when I Apply and press OK the failure still remains. When I go back to the settings the EV3 Uploader is still empty.

I trying to program my EV3 with the c4EV3 since some weeks but still have problems. As I already wrote I am new to Eclipse and if you would have some more documentation or a workaround it would be a great help.

KR Paul

[This is a continuation of: [https://github.com/c4ev3/ev3duder/issues/2](https://github.com/c4ev3/ev3duder/issues/2)]

**Comment by Paul330** [comment]
Do you mean the 110MB installer from http://c4ev3.github.io when you write "big c4ev3"? 

When you start the EV3 "Hello World" Program and open the project properties, is there anything written in the EV3 Uploader (ev3duder) line?

Do you use Windows 7 or 10? I am using a Windows 10 Desktop upgraded from Windows 7. I have already heard, that this could cause some problems.

**Comment by a3f** [comment]
> Do you mean the 110MB installer from http://c4ev3.github.io when you write "big c4ev3"?

Yes.

> When you start the EV3 "Hello World" Program and open the project properties, is there anything written in the EV3 Uploader (ev3duder) line?

Yes, `C:\ev3\uploader`. You should see this also when creating a new project:
<img width="601" alt="screen shot 2017-04-15 at 15 51 06" src="https://cloud.githubusercontent.com/assets/5204368/25064093/9c8d779c-21f3-11e7-840f-822846ec2ee6.png">
<img width="604" alt="screen shot 2017-04-15 at 15 51 16" src="https://cloud.githubusercontent.com/assets/5204368/25064098/9f99ac30-21f3-11e7-8c9e-36eb21649868.png">
<img width="603" alt="screen shot 2017-04-15 at 15 51 24" src="https://cloud.githubusercontent.com/assets/5204368/25064099/a256108a-21f3-11e7-94db-88a1419c5e70.png">
<img width="604" alt="screen shot 2017-04-15 at 15 51 29" src="https://cloud.githubusercontent.com/assets/5204368/25064100/a45391d2-21f3-11e7-8b95-d0e198927066.png">

> Do you use Windows 7 or 10? I am using a Windows 10 Desktop upgraded from Windows 7. I have already heard, that this could cause some problems.

Windows 10, but it was tested on Windows 7 and 8 too.

By the way, you should not need to set search paths yourself for system headers and setting them to your local MinGW installation is wrong.

**Comment by Paul330** [comment]
I know that manually add system headers is not the correct way.^^ But it helped to reduce the errors. When I start a new project for EV3 "Hello World, I have the same like you posted above. Only the toolchain path is filled.

![image](https://cloud.githubusercontent.com/assets/27554412/25064171/05cf1fd4-21f5-11e7-8052-b3dbeec39361.png)

But when I finish and the source is opened I get 3 errors.

![image](https://cloud.githubusercontent.com/assets/27554412/25064176/2b1c3e0c-21f5-11e7-9eac-a6e4e081863c.png)

You don't have these?

**Comment by a3f** [comment]
> I know that manually add system headers is not the correct way.

It's not even a workaround, even if it were to compile, it would probably crash on the EV3. Header contents are quite implementation-specific.

> You don't have these?

No, I don't. Could you try leave the Toolchain path empty in the wizard?

**Comment by Paul330** [comment]
Ah. I understand. 

I left the path empty but it didn't change anything. I tryed to build the project and got another failure.

![image](https://cloud.githubusercontent.com/assets/27554412/25064243/bad3e4d6-21f6-11e7-9ea8-15a2106c1ac3.png)

**Comment by a3f** [comment]
Do you have the same problem with C projects? What about that EV3_Test1 project that has no error mark?

**Comment by Paul330** [comment]
No, other projects work fine. The EV3_Test1 has no error marks because I included the string header manually.^^

**Comment by a3f** [comment]
Did you miss a comma…? (No other projects work vs. No, other projects work)

**Comment by Paul330** [comment]
Edited my comment. ^^

**Comment by a3f** [comment]
So it finds ev3duder now, but not the C++ headers? Could you confirm that uploading the C hello world example works?

**Comment by Paul330** [comment]
No. It still doesn't find the ev3duder.

![image](https://cloud.githubusercontent.com/assets/27554412/25064314/27e582ea-21f8-11e7-8404-7ea932330bdd.png)

I don't know why the EV3 uploader (ev3duder) is empty.

**Comment by a3f** [comment]
So other projects don't work fine? You lost me there…
I created a temporary IRC channel `#c4ev3` on Freenode. I think pair debugging over a forum might not be the most efficient way, if we are both online at the same time.
If you have no IRC client installed, you can use https://webchat.freenode.net/

I'll update this issue if we figure out.

**Comment by Paul330** [comment]
Sorry. Other c++ projects with MinGW toolchain work without any problems.

One moment pls.

**Comment by a3f** [comment]
Changing the workspace fixed it.
