### ISSUE TITLE
HELP - ME Error ELF file.

### ISSUE THREAD

**Issue by ygorseiji** [c4ev3/EV3-Eclipse-Plugin#6]
we are using c4ev3 and we wanted to report a bug on the site in the Elipse plugins part (https://github.com/c4ev3/EV3-Eclipse-Plugin#starter-file) in the "available here" section there is no file and we are problem in the uploud part because the ELF file is not found. I was wondering if you could help us, thanks!

**Comment by a3f** [comment]
I added the link. Normally, you should not need to interact with LMS in any way. The LMS file just bootstraps the C/C++ application that you have compiled to an ELF executable. Could you elaborate, what steps you took and what exactly doesn't work? Any error messages? Screenshots?

Also, I am a bit curious, you say "we are using c4ev3", where's that? And for what? =)

**Comment by ygorseiji** [comment]
Sorry for the lack of education, we are students of the Federal University of Uberlândia (Brazil), I am students of Computer Engineering and work in a laboratory that develops research on educational robotics and Artificial Intelligence, not only us but also a teacher at the Federal University of Goiás (Brazil) who also works with Robotics Educational is looking for a C platform for Ev3.
We are with a project of teaching robotics class in lego using the C language for incoming students in the course of Computer Science and we found very good c4ev3, however we have the problem of uploud, follow the attached error, thank you very much for the feedback.
Obs: We are using Windowns
![bug](https://user-images.githubusercontent.com/36743193/36574015-524443e8-1822-11e8-9bbe-1abf6a2ef474.JPG)

**Comment by a3f** [comment]
Did you compile by clicking the build "hammer" icon first?
Cool! Thanks for the background information. It's nice to learn about who ponders using it :-)

**Comment by a3f** [comment]
I assume this was the issue? Please tell if there is any more help needed.

**Comment by Omar-Alzaabi** [comment]
Hello, I am a professional robot builder and programmer.I have been programming with ev3 small basic but I wanted to improve my self in programming, so I decided to learn on C4Ev3, but the problem is when I upload "Hello World" program to the ev3 eclipse gives message that the program doesn't exist, in fact I have saved the program and hammered it, also GCC has last version.

Can you please solve for me this issue :) !

**Comment by a3f** [comment]
Please open a new separate issue with a description of what you've done and the exact error message you got as well as how the EV3 is connected.
